### ISSUE TITLE
Ex2 : Write Simple REST Server @Local in Typescript

### ISSUE THREAD

**Issue by anu1667** [Eshwari247/init_exercises#2]
### Simple REST Server @Local

Develop a RESTful API that meets the following requirements: 
       - If we makes GET at the Endpoint, it returns 0.  
       - If we make POST at the Endpoint, it returns the result of multiplication

The program should be developed using node.js and javascript

For example:
       - If we make GET to [http://localhost:8080/cal](http://localhost:8080/cal%E3%81%ABGET%E3%81%99%E3%82%8B%E3%81%A8) it returns {“answer”: “0”}
       - It we POST {A: 1, B:2} to [http://localhost:8080/cal](http://localhost:8080/cal%E3%81%AB)  it returns {“answer”: “2”}

The test should be done using the curl command
- `curl http://localhost:8080/cal`
- `curl -X POST -d '{"A":1,"B":2}' -H "Content-Type: application/json" http://localhost:8080/cal`

**Comment by Eshwari247** [comment]
ref links - 
learning & implementing REST APIs - 
https://www.freecodecamp.org/news/rest-api-design-best-practices-build-a-rest-api/
https://blog.logrocket.com/how-to-set-up-node-typescript-express/
https://blog.postman.com/how-to-create-a-rest-api-with-node-js-and-express/
https://www.tutorialspoint.com/nodejs/nodejs_restful_api.htm
https://idratherbewriting.com/learnapidoc/docapis_understand_curl.html


typescript - error - Could not find a declaration file for module 'express'. '/Users/eshwarijaladurgam/node_modules/express/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`

fix - import {Request, Response } from 'express';
import express = require('express');
import* as bodyParser from 'body-parser';
