### ISSUE TITLE
Look up AWS Lambda and Serverless Framework

### ISSUE THREAD

**Issue by anu1667** [Eshwari247/init_exercises#3]
- [x] Study about AWS Lambda
- [x] Study about Serverless framework

**Comment by Eshwari247** [comment]
ref links - 
https://www.serverless.com/aws-lambda
https://www.youtube.com/watch?v=xPzDS2TkEXQ

To learn via course - 
https://www.udemy.com/course/aws-lambda-serverless/
or 
https://www.udemy.com/course/aws-lambda-serverless-architecture/

**Comment by Eshwari247** [comment]
AWS Lambda -  single purpose functions triggered by events. 

Event driven execution - HTTP. Requests, S3 buckets, DynamoDB tables, custom events using Amazon CloudWatch Events or AWS SDK.
Environment & Runtime - AWS provides resources - CPU, memory, network as the infra, 
      Regarding runtime - Node.js, Python, Java, C#, Ruby
3)   Scalability - when the events increase, the functions scale automatically
4)   Isolation  - the functions are stateless, there’s no persistent state between invocations 


AWS Lambda  - the background running architecture 

Your code -> Lambda Runtime -> Sandbox -> Guest OS -> Hypervisor -> Host OS -> Hardware

**Comment by Eshwari247** [comment]
Serverless Technology  - in the view of Lambda & Cloud technology 
refers to a cloud computing model where you can run code without provisioning or managing servers.
Event-driven 
Stateless
Scalability , Elasticity
Automatic Scaling 
Pay per use
Reduction in Overhead
Availability & Fault tolerance
Integration of AWS lambda functions to other applications 
In terms of Lambda - Amazon API Gateway - links to the APIs

**Comment by Eshwari247** [comment]
API Gateway Lambda  - API Gateway and AWS Lambda often work together to create serverless applications and expose RESTful or HTTP endpoints for those applications

API definition :- abstracting the implementation, exposing objects or actions the development needs

What does it do - create, maintain, publish, monitor, secure

Client makes a request to the API gets a response, API talks to the web server and database

API Gateway & Lambda - One of the primary use cases of API Gateway is to integrate with AWS Lambda functions. You can specify that a particular route and HTTP method should trigger a specific Lambda function when a request is made to that endpoint. This integration is highly customisable and can be used to pass data from the HTTP request to the Lambda function as input.
the interaction - proxy or integration, 
Proxy - metadata as wrapper
Integration - apache tool- VTL to encrypt 

API distinctive features

- Authorization 
- Caching - quick response , minimise load
- Throttling - limiting  requests among APIs 
- Security - VPC links, private integrations
- Stages  - Prod, Beta, Dev
- Metrics - Cloud watch, Cloud trail, Config
- Certificates - how it works => API Gateway -> Certificate->Amazon E2C instance
- Canary releases - Cloud watch checks the API , prod environment when it works well else pushed to canary. 
- Custom Domain -  API to a custom domain, allowing you to use your own domain name for the API endpoints
